language: cpp
compiler:
  - clang
before_install:
  - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y #for qt5
  - sudo apt-get update -qq
  - sudo apt-get install -y qt5-default cmake libtag1-dev libboost-dev libsndfile1-dev libjack-dev libmad0-dev libvorbis-dev liblo-dev lv2core liblilv-dev libvamp-hostsdk3 vamp-plugin-sdk
script: mkdir -p ext/yaml-cpp-build/ && pushd ext/yaml-cpp-build/ && cmake ../yaml-cpp/ && make && popd && qmake -recursive -spec linux-clang && make
notifications:
  email:
    - alex@x37v.info
