database:
#  adapter: mysql2
#  database: datajockey
#  username: developer
#  password: pass
  adapter: sqlite3
  database: /home/alex/.datajockey/database.sqlite3
  pool: 5
  timeout: 5000
eq:
  uri: "http://plugin.org.uk/swh-plugins/dj_eq"
  controls: ["lo", "mid", "hi"]
  #dbscale: [0.0, 0.0, 0.0]
  #presetfile: /path/to/present.ttl
osc:
  in_port: 10001
  out:
    address: localhost
    port: 10010
annotation:
  files: ~/.datajockey/annotation/
  beat_locations:
    smoothing: 10
interpreter: false
