database:
  adapter: mysql2
  database: datajockey
  username: developer
  password: pass
#  adapter: sqlite3
#  database: /home/alex/.datajockey/database.sqlite3
#  pool: 5
#  timeout: 5000
osc_port: 10001
annotation:
  files: ~/.datajockey/annotation-new/
  beat locations:
    smoothing: 10
interpreter: false
